# Generated by Django 5.2.5 on 2025-08-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('music', 'Music'), ('success', 'Technology'), ('arts', 'Arts & Culture'), ('food', 'Food & Drink')], default='other'),
        ),
    ]
