# Generated by Django 5.2.5 on 2025-08-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_events_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name="events",
            name="category",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("music", "Music"),
                    ("technology", "Technology"),
                    ("arts", "Arts & Culture"),
                    ("food", "Food & Drink"),
                ],
                default="other",
            ),
        ),
    ]
