# Generated by Django 5.2.5 on 2025-08-30 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_saveddates_alter_events_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SavedDates",
        ),
    ]
