# Generated by Django 5.2.5 on 2025-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_delete_saveddates"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
