# Generated by Django 5.2.5 on 2025-08-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_events_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
