# Generated by Django 5.2.5 on 2025-09-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_events_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="ticke_amount",
            field=models.IntegerField(default=0),
        ),
    ]
