# Generated by Django 5.2.5 on 2025-09-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_events_ticke_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="ticke_amount",
            new_name="ticket_amount",
        ),
    ]
