# Generated by Django 5.2.5 on 2025-09-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_rename_ticke_amount_events_ticket_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="ticket_amount",
            new_name="available_ticket",
        ),
    ]
