# Generated by Django 5.2.5 on 2025-09-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_events_available_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="available_ticket",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
