# Generated by Django 5.2.5 on 2025-09-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_alter_events_available_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="events",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
