# Generated by Django 5.2.5 on 2025-09-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_events_is_published_events_latitude_events_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="is_published",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
