# Generated by Django 5.2.5 on 2025-09-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_events_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="category",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("music", "Music"),
                    ("technology", "Technology"),
                    ("arts", "Arts & Culture"),
                    ("food", "Food & Drink"),
                    ("sports", "Sports & Fitness"),
                ],
                default="other",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
