# Generated by Django 5.2.5 on 2025-09-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_alter_events_category_alter_events_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="published_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
