# Generated by Django 5.2.5 on 2025-09-16 18:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_events_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
