# Generated by Django 5.2.5 on 2025-09-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_events_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="used_ticket",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
