# Generated by Django 5.2.5 on 2025-09-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_events_used_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="used_ticket",
            field=models.IntegerField(default=0),
        ),
    ]
