# Generated by Django 5.2.5 on 2025-11-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_events_used_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="ticket_bought",
            field=models.IntegerField(default=0),
        ),
    ]
