# Generated by Django 5.2.5 on 2026-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_events_ticket_bought"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
