# Generated by Django 5.2.5 on 2026-04-21 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_events_is_private"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["is_private", "start_date", "category"],
                name="events_even_is_priv_715954_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["start_date"], name="events_even_start_d_eb087d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["category"], name="events_even_categor_a365dc_idx"
            ),
        ),
    ]
