services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  django-web:
    build: .
    container_name: django-docker
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
    depends_on:
      - django-web
volumes:
  postgres_data:
  static_volume: