# Generated by Django 5.2.5 on 2025-09-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="reference",
            field=models.CharField(default="ORD-92115", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="order_id",
            field=models.CharField(blank=True, default="ORD-92115", unique=True),
        ),
    ]
