# Generated by Django 5.2.5 on 2025-09-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_registration_reference_alter_registration_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="order_id",
            field=models.CharField(blank=True, default="ORD-d0e5f", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="reference",
            field=models.CharField(default="REF-d0e5f", unique=True),
        ),
    ]
