# Generated by Django 5.2.5 on 2025-09-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_registration_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="unique_code",
            field=models.CharField(default="TIK-778eb", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="order_id",
            field=models.CharField(blank=True, default="ORD-dc496", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="reference",
            field=models.CharField(default="REF-dc496", unique=True),
        ),
    ]
