# Generated by Django 5.2.5 on 2025-09-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_registration_updated_at_ticket_unique_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="order_id",
            field=models.CharField(blank=True, default="ORD-96e4a", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="reference",
            field=models.CharField(default="REF-96e4a", unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="unique_code",
            field=models.CharField(default="TIK-5f978", unique=True),
        ),
    ]
