# Generated by Django 5.2.5 on 2025-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_alter_registration_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="order_id",
            field=models.CharField(blank=True, default="ORD-4dd2a", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="reference",
            field=models.CharField(default="REF-4dd2a", unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="unique_code",
            field=models.CharField(default="TIK-1bf77", unique=True),
        ),
    ]
