# Generated by Django 5.2.5 on 2025-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_alter_registration_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="scanned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="order_id",
            field=models.CharField(blank=True, default="ORD-c7aca", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="reference",
            field=models.CharField(default="REF-c7aca", unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="unique_code",
            field=models.CharField(default="TIK-c9a23", unique=True),
        ),
    ]
