# Generated by Django 5.2.5 on 2025-09-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0018_alter_registration_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="order_id",
            field=models.CharField(blank=True, default="ORD-7ecb0", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="reference",
            field=models.CharField(default="REF-7ecb0", unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="unique_code",
            field=models.CharField(default="TIK-7bb85", unique=True),
        ),
    ]
