# Generated by Django 5.2.5 on 2025-09-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0022_alter_registration_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="order_id",
            field=models.CharField(blank=True, default="ORD-b4acd", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="reference",
            field=models.CharField(default="REF-b4acd", unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="unique_code",
            field=models.CharField(default="TIK-5e4bc", unique=True),
        ),
    ]
