# Generated by Django 5.2.5 on 2025-09-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0024_alter_registration_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="order_id",
            field=models.CharField(blank=True, default="ORD-4e29d", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="reference",
            field=models.CharField(default="REF-4e29d", unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="unique_code",
            field=models.CharField(default="TIK-0d3d4", unique=True),
        ),
    ]
