# Generated by Django 5.2.5 on 2025-11-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0030_alter_registration_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="order_id",
            field=models.CharField(blank=True, default="ORD-1b686", unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="reference",
            field=models.CharField(default="REF-1b686", unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="unique_code",
            field=models.CharField(default="TIK-ef762", unique=True),
        ),
    ]
